name: Kali-Linux-RDP

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: start
      env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: |
       wget -O kali.sh https://raw.githubusercontent.com/oussamabriedj/macOS/main/kali.sh > /dev/null 2>&1
        chmod +x kali.sh
        ./kali.sh "$NGROK_AUTH_TOKEN"
 
