name: Kali-Linux-RDP

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: start
      run: |
        wget -O kali.sh https://bit.ly/3EM0kdd > /dev/null 2>&1
        chmod +x kali.sh
        ./kali.sh
 
